name=input()
#print("name is {}".format(name))
age=int(input())
#print("age of {} is {}".format(name,age))
#print(f"age of {name} is {age}")
add=input()
qua=input()
#print("Student name : {}\nStudent age : {}\nStudent address : {}\nStudent qualification : {}\n".format(name,age,add,qua))
print(f"Student name : {name}\nStudent age : {age}\nStudent address : {add}\nStudent qualification : {qua}\n")