ascii_value=ord("a")
print("a",chr(97))
ascii_value1=ord("  ")
ascii_value2=ord("A")
ascii_value3=ord("Z")
print("a",ascii_value)
print("z",ascii_value1)
print("A",ascii_value2)
print("Z",ascii_value3)
print(65+32)
print(90+32)
print(97-32)
print(122-32)
